export const DOCTORS_CACHE_TTL_MS = 60 * 1000;
export const SITE_DOCTORS_CACHE_TTL_MS = 60 * 1000;
export const SLOTS_CACHE_TTL_MS = 30 * 1000;
export const CALENDAR_AVAILABILITY_CACHE_TTL_MS = 60 * 1000;

export const SITE_DOCTORS_CACHE_MAX_ENTRIES = 100;
export const SLOTS_CACHE_MAX_ENTRIES = 200;
export const CALENDAR_AVAILABILITY_CACHE_MAX_ENTRIES = 200;
